function [lambda bandw c hbar ph wc gaun mrabi FWHM1 gauf gauf1 dt ww Nf tt] = variable(~)
%
lambda = 400.;                % in nm
lambda = lambda*1e-9;         % in m
bandw = 5;                    % Pulse bandwidth in nm
bandw = bandw*1e-9;           % in m
N = 1024;                     % Number of points in the pulse
NN = 2^19;                    % Number of points in the Fourier result
c = 299792458;                % Speed of light in m/s
hbar = (6.62e-34)/(2.*pi);      % Plancks constant in Js.
ph = 0;                       % Instanteneous pulse phase
wc = (2.*pi*c)/lambda;        % Center Frequency of Laser pulse
% d = 1;                        % dipole moment which is...
mrabi = 1;                    % ...essentially overridden by maximum Rabi
FWHM1 = 1e15*(lambda^2)/(c*bandw);  % Time FWHM in fs
offset = lambda - 2.*bandw;
start = 0.;
stop = 4.*bandw;
w = linspace(start,stop,N);
w0 = (stop - start)/2.;
gaun1 = exp(-4*log(2.)*((w-w0)/bandw).^2);
gaun = gaun1.*exp(1i*(wc*(w-w0)+ph));
% gaun = gaun1.*(cos(wc*(w-w0)+ph));
ww = (w+offset)*1e9;                      % in nm (for plotting)
gau = fftshift(fft(gaun,NN));
t = (1:NN); 
[FWHM,xmin] = fwhm(t,gau);
peakpt = xmin + round(FWHM/2);
start = peakpt - 2*FWHM;
stop = peakpt + 2*FWHM;
gauf1 = abs(gau(start:stop));
gauf = gau(start:stop);
Nf = length(gauf1);
tt = t(start:stop);
dt = 1e-15*FWHM1/FWHM;
tt = dt*(tt - tt(1));
% tt0 = (tt(Nf)-tt(1))/2.;
% gauf = gauf1.*(cos(wc*(tt-tt0)+ph));
gauf=gauf/max(gauf1);
