function [lambda bandw c hbar ph wc gaun mrabi FWHM1 gauf gauf1 dt ww Nf tt] = variable(~)
%
lambda = 400.;                
lambda = lambda*1e-9;         % in metres
bandw = 5;                    
bandw = bandw*1e-9;           % Pulse bandwidth in metres
N = 1024;                     % Number of points in the pulse
Fourierpoint = 2^19;          % Number of points in the Fourier result
c = 299792458;                
hbar = (6.62e-34)/(2.*pi);    % in J/s
ph = 0;                       % Instanteneous pulse phase
wc = (2.*pi*c)/lambda;        % Center Frequency of Laser
% d = 1;                      % dipole moment
mrabi = 1;                    
FWHM1 = 1e15*(lambda^2)/(c*bandw);  % Time FWHM in fs
offset = lambda - 2.*bandw;
start = 0.;
stop = 4.*bandw;
w = linspace(start,stop,N);
w0 = (stop - start)/2.;
gaun1 = exp(-4*log(2.)*((w-w0)/bandw).^2);
gaun = gaun1.*exp(1i*(wc*(w-w0)+ph));
% gaun = gaun1.*(cos(wc*(w-w0)+ph));
ww = (w+offset)*1e9;                     
gau = fftshift(fft(gaun,Fourierpoint));
t = (1:Fourierpoint); 
[FWHM,xmin] = fwhm(t,gau);
peakpt = xmin + round(FWHM/2);
start = peakpt - 2*FWHM;
stop = peakpt + 2*FWHM;
gauf1 = abs(gau(start:stop));
gauf = gau(start:stop);
Nf = length(gauf1);
tt = t(start:stop);
dt = 1e-15*FWHM1/FWHM;
tt = dt*(tt - tt(1));
% tt0 = (tt(Nf)-tt(1))/2.;
% gauf = gauf1.*(cos(wc*(tt-tt0)+ph));
gauf=gauf/max(gauf1);
